LANE_ORDER = ("Lane_1", "Lane_2", "Lane_3", "Lane_4")
NETWORK_LANE_IDS = ("Lane_1", "Lane_3", "Lane_4")
REMOTE_CLIENT_LANE_IDS = ("Lane_3", "Lane_4")
PI_CAMERA_LANE_ID = "Lane_1"
LOCAL_SERVER_LANE_ID = "Lane_2"
RUNTIME_STATE_PATH = "runtime/traffic_state.json"
RUNTIME_FRAMES_DIR = "runtime_frames"

SERVER_BIND_HOST = "0.0.0.0"
SERVER_CONNECT_HOST = "10.70.70.18"
VIDEO_PORT = 5555
CONTROL_PORT = 6666
CONTROLLER_ID = "Intersection_Main"

SOCKET_TIMEOUT_SECONDS = 5.0
RECONNECT_DELAY_SECONDS = 3.0
MAX_LINE_BYTES = 256
MAX_FRAME_BYTES = 2_000_000

FRAME_WIDTH = 320
FRAME_HEIGHT = 240
JPEG_QUALITY = 70
CAMERA_FPS = 6
FRAME_SEND_INTERVAL_SECONDS = 1.0 / CAMERA_FPS
FRAME_STALE_SECONDS = 5.0
LOCAL_SERVER_CAMERA_SOURCE = 0
PI_CAMERA_SOURCE = 0

MODEL_PATH = "best.pt"
SHOW_DEBUG_WINDOWS = False

MIN_GREEN_SECONDS = 6
MAX_GREEN_SECONDS = 15
SECONDS_PER_VEHICLE = 1
DEFAULT_GREEN_SECONDS = MIN_GREEN_SECONDS
YELLOW_SECONDS = 2
ALL_RED_SECONDS = 1

